version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ../../strategic-dcs/engine/shared_data:/app/shared_data
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src --app-dir src
    networks:
      - nginx-proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
