version: "3.8"
services:

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: aij8Eith
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432/tcp"
    networks:
      - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      # TODO: add the correct path for the data folder.
      - ./backend/data:/app/data
      - /data/sdcs/shared_data:/app/shared_data
    env_file:
      - .env
    command: uvicorn sdcs.main:app --host 0.0.0.0 --port 8000 --app-dir src
    networks:
      - backend
      - database

  varnish:
    image: varnish
    env_file:
      - .env
    volumes:
      - ./cache/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish/varnishd:exec,size=2G,mode=0777
    environment:
      VIRTUAL_PATH: /api
      VARNISH_SIZE: 2G
    dns: 127.0.0.11
    networks:
      - backend
      - nginx-proxy

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      VIRTUAL_PATH: /
    networks:
      - nginx-proxy

networks:
  database:
  backend:
  nginx-proxy:
    external: true
