version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # TODO: add the correct path for the data folder.
      - ./backend/data:/app/data
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: strategic-dcs.com,www.strategic-dcs.com
      LETSENCRYPT_HOST: strategic-dcs.com
      VIRTUAL_PATH: /web/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir src
    networks:
      - nginx-proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      VIRTUAL_HOST: strategic-dcs.com,www.strategic-dcs.com
      LETSENCRYPT_HOST: strategic-dcs.com
      VIRTUAL_PATH: /web
      VITE_FQDN: ${FQDN}
      VITE_DISCORD_CLIENT_ID: ${DISCORD_OAUTH_CLIENT_ID}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
