version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      # TODO: add the correct path for the data folder.
      - ./backend/data:/app/data
      - /data/sdcs/shared_data:/app/shared_data
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir src
    networks:
      - internal

  varnish:
    image: varnish
    env_file:
      - .env
    volumes:
      - ./cache/default.vcl:/etc/varnish/default.vcl:ro
      - type: tmpfs
        target: /var/lib/varnish/varnishd
    environment:
      VIRTUAL_PATH: /api
      VARNISH_SIZE: 2G
    networks:
      - nginx-proxy
      - internal

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      VIRTUAL_PATH: /
    networks:
      - nginx-proxy

networks:
  internal:
  nginx-proxy:
    external: true
