version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ../../strategic-dcs/engine/shared_data:/app/shared_data
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src --app-dir src
    networks:
      - internal

  varnish:
    image: varnish
    env_file:
      - .env
    volumes:
      - ./cache/default.vcl:/etc/varnish/default.vcl:ro
      - type: tmpfs
        target: /var/lib/varnish/varnishd
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /api
      VARNISH_SIZE: 2G
    networks:
      - nginx-proxy
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /
    networks:
      - internal

networks:
  internal:
  nginx-proxy:
    external: true
